kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: admin-role-binding-network-system
subjects:
- kind: ServiceAccount
  name: network-service-account
  namespace: network-system
roleRef:
  kind: ClusterRole
  name: admin-network-system
  apiGroup: rbac.authorization.k8s.io
